import type { DemoState } from "./domain";
export function seed(): DemoState {
  return {
    version: 2,
    suppliers: [
      { id: "SUP-001", reference: "PROV-DEMO-01", name: "Suministros del Valle · Ficticio" },
      { id: "SUP-002", reference: "PROV-DEMO-02", name: "Distribuidora Norte · Ficticia" },
    ],
    purchases: [{
      id: "OC-001", reference: "OC-DEMO-001", supplierId: "SUP-001", date: "2026-09-28", expectedDate: "2026-10-02", cancelled: false,
      lines: [{ id: "LINE-001", sku: "MED-DEMO-01", product: "Inhalador de demostración A", category: "Farmacia", ordered: 20, received: 0, unitCostCents: 20000, minimum: 10, priceCents: 32000 }],
    }],
    receipts: [],
    patients: [
      {
        id: "DEMO-001",
        name: "Lucía Montes · Ficticia",
        birth: "1988-04-12",
        phone: "Sin teléfono real",
        tag: "Seguimiento",
      },
      {
        id: "DEMO-002",
        name: "Andrés Valle · Ficticio",
        birth: "1970-11-05",
        phone: "Sin teléfono real",
        tag: "Primera visita",
      },
      {
        id: "DEMO-003",
        name: "Elena Robles · Ficticia",
        birth: "1995-06-20",
        phone: "Sin teléfono real",
        tag: "Estudio",
      },
      {
        id: "DEMO-004",
        name: "Mateo Silva · Ficticio",
        birth: "1982-02-18",
        phone: "Sin teléfono real",
        tag: "Seguimiento",
      },
      {
        id: "DEMO-005",
        name: "Sofía Rivera · Ficticia",
        birth: "1963-09-22",
        phone: "Sin teléfono real",
        tag: "Primera visita",
      },
    ],
    visits: [
      {
        id: "CITA-001",
        patientId: "DEMO-001",
        date: "2026-09-28",
        time: "09:00",
        service: "Consulta de seguimiento",
        status: "Finalizada",
        externalRef: "Ejemplo DA-1001",
      },
      {
        id: "CITA-002",
        patientId: "DEMO-002",
        date: "2026-09-28",
        time: "09:40",
        service: "Primera consulta",
        status: "En consulta",
        externalRef: "Ejemplo DA-1002",
      },
      {
        id: "CITA-003",
        patientId: "DEMO-003",
        date: "2026-09-28",
        time: "10:20",
        service: "Espirometría",
        status: "En espera",
        externalRef: "Ejemplo DA-1003",
      },
      {
        id: "CITA-004",
        patientId: "DEMO-004",
        date: "2026-09-28",
        time: "11:00",
        service: "Consulta de seguimiento",
        status: "Confirmada",
        externalRef: "Ejemplo DA-1004",
      },
      {
        id: "CITA-005",
        patientId: "DEMO-005",
        date: "2026-09-28",
        time: "11:40",
        service: "Primera consulta",
        status: "Confirmada",
        externalRef: "Ejemplo DA-1005",
      },
    ],
    lots: [
      {
        id: "LOT-01",
        sku: "MED-DEMO-01",
        product: "Inhalador de demostración A",
        category: "Farmacia",
        batch: "SIM-2601",
        expires: "2026-10-20",
        quantity: 8,
        minimum: 10,
        priceCents: 32000,
        quarantined: false,
      },
      {
        id: "LOT-02",
        sku: "MED-DEMO-01",
        product: "Inhalador de demostración A",
        category: "Farmacia",
        batch: "SIM-2602",
        expires: "2027-05-31",
        quantity: 24,
        minimum: 10,
        priceCents: 32000,
        quarantined: false,
      },
      {
        id: "LOT-03",
        sku: "MED-DEMO-02",
        product: "Solución de demostración B",
        category: "Farmacia",
        batch: "SIM-2603",
        expires: "2026-08-31",
        quantity: 6,
        minimum: 5,
        priceCents: 8500,
        quarantined: false,
      },
      {
        id: "LOT-04",
        sku: "INS-001",
        product: "Boquilla desechable · ejemplo",
        category: "Insumos",
        batch: "INS-2601",
        expires: "2028-03-31",
        quantity: 45,
        minimum: 20,
        priceCents: 2000,
        quarantined: false,
      },
      {
        id: "LOT-05",
        sku: "INS-002",
        product: "Filtro de espirometría · ejemplo",
        category: "Insumos",
        batch: "INS-2602",
        expires: "2027-06-30",
        quantity: 12,
        minimum: 15,
        priceCents: 4500,
        quarantined: false,
      },
      {
        id: "LOT-06",
        sku: "INS-003",
        product: "Mascarilla · ejemplo",
        category: "Insumos",
        batch: "INS-2603",
        expires: "2028-09-30",
        quantity: 80,
        minimum: 25,
        priceCents: 1000,
        quarantined: true,
      },
    ],
    movements: [],
    notes: [],
    payments: [
      {
        id: "PAGO-001",
        reference: "DEMO-CAJA-001",
        patientId: "DEMO-001",
        concept: "Consulta · importe ilustrativo",
        amountCents: 100000,
        method: "Efectivo",
        date: "2026-09-28",
        reversed: false,
      },
      {
        id: "PAGO-002",
        reference: "DEMO-CAJA-002",
        patientId: "DEMO-002",
        concept: "Consulta · importe ilustrativo",
        amountCents: 100000,
        method: "Tarjeta",
        date: "2026-09-28",
        reversed: false,
      },
    ],
    equipment: [
      {
        id: "EQ-001",
        name: "Espirómetro · ejemplo",
        serial: "DEMO-SPI-01",
        place: "Sala de estudios",
        nextService: "2026-10-15",
        status: "Disponible",
      },
      {
        id: "EQ-002",
        name: "Oxímetro · ejemplo",
        serial: "DEMO-OXI-01",
        place: "Consultorio 1",
        nextService: "2027-01-15",
        status: "Disponible",
      },
      {
        id: "EQ-003",
        name: "Nebulizador · ejemplo",
        serial: "DEMO-NEB-01",
        place: "Terapia respiratoria",
        nextService: "2026-09-30",
        status: "En mantenimiento",
      },
    ],
  };
}
